export let textLanguages = {
  "hey there! thank you so much for using clear": {
    jp: "ちょっと、そこ！いつもクリアをご利用いただき誠にありがとうございます",
    es: "¡hola! muchas gracias por usar claro",
    hi: "सुनो! क्लियर का उपयोग करने के लिए आपका बहुत-बहुत धन्यवाद",
    ru: "Привет! большое спасибо за использование ясности",
    fr: "salut! merci beaucoup d'utiliser clear",
  },
  "add some new games using the sidebar buttons": {
    jp: "サイドバーボタンを使用して新しいゲームを追加します",
    es: "agregue algunos juegos nuevos usando los botones de la barra lateral",
    hi: "साइडबार बटनों का उपयोग करके कुछ नए गेम जोड़ें",
    ru: "добавьте несколько новых игр с помощью кнопок боковой панели",
    fr: "ajoutez de nouveaux jeux en utilisant les boutons de la barre latérale",
  },
  "create new folders and drag and drop your games into them": {
    jp: "新しいフォルダーを作成し、そこにゲームをドラッグ アンド ドロップします。",
    es: "Crea nuevas carpetas y arrastra y suelta tus juegos en ellas.",
    hi: "नए फ़ोल्डर बनाएं और अपने गेम को उनमें खींचें और छोड़ें",
    ru: "создавайте новые папки и перетаскивайте в них свои игры",
    fr: "créez de nouveaux dossiers et faites-y glisser et déposez vos jeux",
  },
  "dont forget to check out the settings!": {
    jp: "設定を確認することを忘れないでください",
    es: "¡No olvides revisar la configuración!",
    hi: "सेटिंग्स की जांच करना न भूलें!",
    ru: "не забудьте проверить настройки!",
    fr: "n'oubliez pas de vérifier les paramètres !",
  },
  "import steam games": {
    jp: "Steam ゲームをインポートする",
    es: "importar juegos de steam",
    hi: "स्टीम गेम्स आयात करें",
    ru: "импортировать игры из Steam",
    fr: "importer des jeux Steam",
  },
  "might not work perfectly!": {
    jp: "完全に動作しない可能性があります!",
    es: "¡Puede que no funcione perfectamente!",
    hi: "हो सकता है कि यह पूरी तरह से काम न करे!",
    ru: "может работать не идеально!",
    fr: "pourrait ne pas fonctionner parfaitement !",
  },
  "new game": {
    jp: "新しいゲーム",
    es: "nuevo juego",
    hi: "नया खेल",
    ru: "новая игра",
    fr: "nouveau jeu",
  },
  "open settings": {
    jp: "設定を開く",
    es: "configuración abierta",
    hi: "खुली सेटिंग",
    ru: "открыть настройки",
    fr: "ouvrir les paramètres",
  },
  "new folder": {
    jp: "新しいフォルダ",
    es: "nueva carpeta",
    hi: "नया फ़ोल्डर",
    ru: "новая папка",
    fr: "nouveau dossier",
  },
  "open notepad": {
    jp: "メモ帳を開く",
    es: "abrir el bloc de notas",
    hi: "नोटपैड खोलें",
    ru: "открыть блокнот",
    fr: "ouvrir le bloc-notes",
  },
  "close app": {
    jp: "アプリを閉じる",
    es: "cerrar app",
    hi: "ऐप बंद करें",
    ru: "закрыть приложение",
    fr: "fermer l'application",
  },
  "close dialogs": {
    jp: "ダイアログを閉じる",
    es: "cerrar diálogos",
    hi: "संवाद बंद करें",
    ru: "закрывать диалоги",
    fr: "fermer les boîtes de dialogue",
  },
  "search bar": {
    jp: "検索バー",
    es: "barra de búsqueda",
    hi: "खोज पट्टी",
    ru: "панель поиска",
    fr: "barre de recherche",
  },
  "hide sidebar": {
    jp: "サイドバーを隠す",
    es: "esconder barra lateral",
    hi: "किनारे की बाधा को हटाएं",
    ru: "скрыть боковую панель",
    fr: "masquer la barre latérale",
  },
  "quick open game": {
    jp: "クイックオープンゲーム",
    es: "juego abierto rápido",
    hi: "त्वरित खुला खेल",
    ru: "быстро открыть игру",
    fr: "jeu ouvert et rapide",
  },
  "no game file": {
    jp: "ファイルがない",
    es: "ningún archivo",
    hi: "कोई गेम फ़ाइल नहीं",
    ru: "нет файла игры",
    fr: "pas de fichier de jeu",
  },
  "no games found": {
    jp: "ゲームが見つかりません",
    es: "no se han encontrado juegos",
    hi: "कोई गेम नहीं मिला",
    ru: "игры не найдены",
    fr: "aucun jeu trouvé",
  },
  uncategorized: {
    jp: "未分類",
    es: "sin categoría",
    hi: "अवर्गीकृत",
    ru: "без категории",
    fr: "non classé",
  },
  "add game": {
    jp: "ゲームを追加",
    es: "agregar juego",
    hi: "गेम जोड़ें",
    ru: "добавить игру",
    fr: "ajouter un jeu",
  },
  "add folder": {
    jp: "フォルダーを追加",
    es: "agregar carpeta",
    hi: "फ़ोल्डर जोड़ें",
    ru: "добавить папку",
    fr: "ajouter le dossier",
  },
  notepad: {
    jp: "メモ帳",
    es: "bloc",
    hi: "नोटपैड",
    ru: "блокнот",
    fr: "bloc-notes",
  },
  settings: {
    jp: "設定",
    es: "ajustes",
    hi: "समायोजन",
    ru: "настройки",
    fr: "paramètres",
  },
  search: {
    jp: "検索",
    es: "buscar",
    hi: "खोज",
    ru: "поиск",
    fr: "recherche",
  },
  "new update available!": {
    jp: "新しいアップデートが利用可能になりました!",
    es: "¡Nueva actualización disponible!",
    hi: "नई सूचना उपलब्ध है!",
    ru: "доступно новое обновление!",
    fr: "nouvelle mise à jour disponible!",
  },
  "rounded borders": {
    jp: "丸い境界線",
    es: "bordes redondeados",
    hi: "गोलाकार सीमाएँ",
    ru: "закругленные границы",
    fr: "bordures arrondies",
  },
  "game title": {
    jp: "ゲームタイトル",
    es: "título del juego",
    hi: "खेल का शीर्षक",
    ru: "название игры",
    fr: "titre du jeu",
  },
  "folder title": {
    jp: "フォルダタイトル",
    es: "título de la carpeta",
    hi: "फ़ोल्डर शीर्षक",
    ru: "название папки",
    fr: "titre du dossier",
  },
  "quit after opening game": {
    jp: "ゲーム開始後に終了",
    es: "salir después de abrir el juego",
    hi: "खेल शुरू करने के बाद छोड़ दें",
    ru: "выйти после открытия игры",
    fr: "quitter après avoir ouvert le jeu",
  },
  font: {
    jp: "フォント",
    es: "fuente",
    hi: "फ़ॉन्ट",
    ru: "шрифт",
    fr: "Police de caractère",
  },
  "sans serif": {
    jp: "サンセリフ",
    es: "sans serif",
    hi: "सान्स सेरिफ़",
    ru: "без засечек",
    fr: "sans empattement",
  },
  mono: {
    jp: "単核症",
    es: "mononucleosis infecciosa",
    hi: "मोनो",
    ru: "мононуклеоз",
    fr: "mono",
  },
  serif: {
    jp: "セリフ",
    es: "serifa",
    hi: "सेरिफ़",
    ru: "засечка",
    fr: "empattement",
  },
  light: {
    jp: "ライト",
    es: "Ligero",
    hi: "रोशनी",
    ru: "свет",
    fr: "lumière",
  },
  dark: {
    jp: "暗い",
    es: "oscuro",
    hi: "अँधेरा",
    ru: "темный",
    fr: "sombre",
  },
  theme: {
    jp: "テーマ",
    es: "tema",
    hi: "विषय",
    ru: "тема",
    fr: "thème",
  },
  "open library location": {
    jp: "図書館の場所を開く",
    es: "ubicación de la biblioteca abierta",
    hi: "पुस्तकालय का स्थान खोलें",
    ru: "расположение открытой библиотеки",
    fr: "emplacement de la bibliothèque ouverte",
  },
  "these are all the files that the app stores on your pc. you can copy these files to the same location on another pc to get your library there":
    {
      jp: "これらはすべて、アプリが PC に保存するファイルです。これらのファイルを別の PC の同じ場所にコピーして、そこにライブラリを取得できます。",
      es: "Estos son todos los archivos que la aplicación almacena en tu PC. Puedes copiar estos archivos a la misma ubicación en otra PC para llevar tu biblioteca allí.",
      hi: "ये सभी फ़ाइलें हैं जिन्हें ऐप आपके पीसी पर संग्रहीत करता है। आप अपनी लाइब्रेरी को वहां पहुंचाने के लिए इन फ़ाइलों को दूसरे पीसी पर उसी स्थान पर कॉपी कर सकते हैं",
      ru: "это все файлы, которые приложение хранит на вашем компьютере. вы можете скопировать эти файлы в то же место на другом компьютере, чтобы разместить там свою библиотеку.",
      fr: "ce sont tous les fichiers que l’application stocke sur votre PC. vous pouvez copier ces fichiers au même emplacement sur un autre PC pour y placer votre bibliothèque",
    },
  feedback: {
    jp: "フィードバック",
    es: "comentario",
    hi: "प्रतिक्रिया",
    ru: "обратная связь",
    fr: "retour",
  },
  "visit website": {
    jp: "ウェブサイトを訪問",
    es: "visita el sitio web",
    hi: "बेवसाइट देखना",
    ru: "посетите вебсайт",
    fr: "visiter le site Web",
  },
  "made by": {
    jp: "作られた",
    es: "hecho por",
    hi: "द्वारा बनाया गया",
    ru: "сделан",
    fr: "faite par",
  },
  "buy me a coffee": {
    jp: "コーヒーを買ってください",
    es: "cómprame un café",
    hi: "मेरे लिए एक कॉफ़ी खरीदो",
    ru: "купи мне кофе",
    fr: "achète-moi un café",
  },
  "write anything you want over here!": {
    jp: "ここに何でも書いてください！",
    es: "¡Escribe lo que quieras aquí!",
    hi: "यहां पर आप जो चाहें लिखें!",
    ru: "пишите сюда все, что хотите!",
    fr: "écrivez tout ce que vous voulez ici !",
  },
  "add new game": {
    jp: "新しいゲームを追加する",
    es: "agregar nuevo juego",
    hi: "नया गेम जोड़ें",
    ru: "добавить новую игру",
    fr: "ajouter un nouveau jeu",
  },
  favourite: {
    jp: "お気に入り",
    es: "favorita",
    hi: "पसंदीदा",
    ru: "любимый",
    fr: "préféré",
  },
  save: {
    jp: "保存",
    es: "ahorrar",
    hi: "बचाना",
    ru: "сохранять",
    fr: "sauvegarder",
  },
  "grid/cover": {
    jp: "グリッド/カバー",
    es: "rejilla/cubierta",
    hi: "ग्रिड/कवर",
    ru: "сетка/крышка",
    fr: "grille/couvercle",
  },
  hero: {
    jp: "ヒーロー",
    es: "héroe",
    hi: "नायक",
    ru: "герой",
    fr: "héros",
  },
  logo: {
    jp: "ロゴ",
    es: "logo",
    hi: "प्रतीक चिन्ह",
    ru: "логотип",
    fr: "logo",
  },
  icon: {
    jp: "アイコン",
    es: "icono",
    hi: "आइकन",
    ru: "икона",
    fr: "icône",
  },
  "name of game": {
    jp: "ゲームの名前",
    es: "nombre del juego",
    hi: "खेल का नाम",
    ru: "название игры",
    fr: "nom du jeu",
  },
  "auto find assets": {
    jp: "アセットの自動検索",
    es: "búsqueda automática",
    hi: "स्वत: संपत्ति खोजें",
    ru: "автоматический поиск",
    fr: "recherche automatique",
  },
  "find assets": {
    jp: "資産を見つける",
    es: "encontrar activos",
    hi: "संपत्ति खोजें",
    ru: "найти активы",
    fr: "trouver des actifs",
  },
  "locate game": {
    jp: "ゲームを探す",
    es: "localizar juego",
    hi: "खेल का पता लगाएं",
    ru: "найти игру",
    fr: "localiser",
  },
  "right click to empty image selection": {
    jp: "右クリックして画像の選択を空にします",
    es: "clic derecho para vaciar la selección de imágenes",
    hi: "छवि चयन खाली करने के लिए राइट क्लिक करें",
    ru: "щелкните правой кнопкой мыши, чтобы очистить выбор изображения",
    fr: "clic droit pour vider la sélection d'images",
  },
  "add new folder": {
    jp: "新しいフォルダーを追加する",
    es: "agregar nueva carpeta",
    hi: "नया फ़ोल्डर जोड़ें",
    ru: "добавить новую папку",
    fr: "ajouter un nouveau dossier",
  },
  "hide in expanded view": {
    jp: "展開表示で非表示にする",
    es: "ocultar en vista ampliada",
    hi: "विस्तारित दृश्य में छिपाएँ",
    ru: "скрыть в развернутом виде",
    fr: "masquer dans la vue développée",
  },
  "name of folder": {
    jp: "フォルダの名前",
    es: "nombre de la carpeta",
    hi: "फ़ोल्डर का नाम",
    ru: "имя папки",
    fr: "nom du dossier",
  },
  loading: {
    jp: "読み込み中",
    es: "cargando",
    hi: "लोड हो रहा है",
    ru: "загрузка",
    fr: "chargement",
  },
  play: {
    jp: "遊ぶ",
    es: "jugar",
    hi: "खेल",
    ru: "играть",
    fr: "jouer",
  },
  edit: {
    jp: "編集",
    es: "editar",
    hi: "संपादन करना",
    ru: "редактировать",
    fr: "modifier",
  },
  delete: {
    jp: "消去",
    es: "borrar",
    hi: "मिटाना",
    ru: "удалить",
    fr: "supprimer",
  },
  "confirm?": {
    jp: "確認する?",
    es: "¿confirmar?",
    hi: "पुष्टि करना?",
    ru: "подтверждать?",
    fr: "confirmer?",
  },
  "scroll on the image to select a different asset": {
    jp: "画像をスクロールして別のアセットを選択します",
    es: "desplácese por la imagen para seleccionar un activo diferente",
    hi: "किसी भिन्न संपत्ति का चयन करने के लिए छवि पर स्क्रॉल करें",
    ru: "прокрутите изображение, чтобы выбрать другой актив",
    fr: "faites défiler l'image pour sélectionner un autre actif",
  },
  "select the official name of your game": {
    jp: "ゲームの正式名を選択してください",
    es: "selecciona el nombre oficial de tu juego",
    hi: "अपने गेम का आधिकारिक नाम चुनें",
    ru: "выберите официальное название вашей игры",
    fr: "sélectionnez le nom officiel de votre jeu",
  },
  "open containing folder": {
    jp: "含まれているフォルダーを開く",
    es: "carpeta que contiene abierto",
    hi: "धारक फोल्डर खोलें",
    ru: "открыть содержащую папку",
    fr: "ouvrir dossier contenant",
  },
  "current 'steam' folder will be overwritten. confirm?": {
    jp: "現在の「steam」フォルダーは上書きされます。確認する?",
    es: "Se sobrescribirá la carpeta 'Steam' actual. ¿confirmar?",
    hi: "वर्तमान 'स्टीम' फ़ोल्डर अधिलेखित कर दिया जाएगा. पुष्टि करना?",
    ru: "текущая папка Steam будет перезаписана. подтверждать?",
    fr: "Le dossier « Steam » actuel sera écrasé. confirmer?",
  },
  "no game file provided!": {
    jp: "ゲームファイルが提供されていません!",
    es: "¡No se proporciona ningún archivo de juego!",
    hi: "कोई गेम फ़ाइल प्रदान नहीं की गई!",
    ru: "Файл игры не предоставлен!",
    fr: "aucun fichier de jeu fourni !",
  },
  "game launched! enjoy your session!": {
    jp: "ゲームが起動しました！セッションをお楽しみください！",
    es: "¡Juego lanzado! ¡Disfruta tu sesión!",
    hi: "गेम लॉन्च हो गया! अपने सत्र का आनंद लें!",
    ru: "игра запущена! наслаждайтесь сеансом!",
    fr: "jeu lancé ! bonne séance !",
  },
  "you're not connected to the internet :(": {
    jp: "インターネットに接続していません:(",
    es: "No estas conectado a internet :(",
    hi: "आप इंटरनेट से कनेक्ट नहीं हैं :(",
    ru: "у тебя нет подключения к интернету :(",
    fr: "tu n'es pas connecté à internet :(",
  },
  "no folder name": {
    jp: "フォルダ名がありません",
    es: "sin nombre de carpeta",
    hi: "कोई फ़ोल्डर नाम नहीं",
    ru: "нет имени папки",
    fr: "pas de nom de dossier",
  },
  "is already in your library": {
    jp: "すでにライブラリにあります",
    es: "ya está en tu biblioteca",
    hi: "आपकी लाइब्रेरी में पहले से ही मौजूद है",
    ru: "уже в вашей библиотеке",
    fr: "est déjà dans votre bibliothèque",
  },
  "no game name": {
    jp: "ゲーム名なし",
    es: "sin nombre de juego",
    hi: "कोई गेम नाम नहीं",
    ru: "нет названия игры",
    fr: "pas de nom de jeu",
  },
  "no folder name": {
    jp: "フォルダ名がありません",
    es: "sin nombre de carpeta",
    hi: "कोई फ़ोल्डर नाम नहीं",
    ru: "нет имени папки",
    fr: "pas de nom de dossier",
  },
  "couldn't find that game :(": {
    jp: "そのゲームは見つかりませんでした:(",
    es: "no pude encontrar ese juego :(",
    hi: "वह गेम नहीं मिल सका :(",
    ru: "не нашел эту игру :(",
    fr: "je n'ai pas trouvé ce jeu :(",
  },
  "couldn't find any assets :(": {
    jp: "アセットが見つかりませんでした:(",
    es: "no pude encontrar ningún activo :(",
    hi: "कोई संपत्ति नहीं मिल सकी :(",
    ru: "не нашел никаких активов :(",
    fr: "je n'ai trouvé aucun élément :(",
  },
  "couldn't find": {
    jp: "見つかりませんでした",
    es: "no pude encontrar",
    hi: "नहीं मिल सका",
    ru: "не смог найти",
    fr: "je n'ai pas pu trouver",
  },
  "sorry but there was an error \n reading your steam library :(": {
    jp: "申し訳ありませんが、Steam ライブラリの読み取り中にエラーが発生しました:(",
    es: "Lo siento pero hubo un error \n al leer tu biblioteca de Steam :(",
    hi: "क्षमा करें, लेकिन आपकी स्टीम लाइब्रेरी को पढ़ने में त्रुटि हुई :(",
    ru: "извините, но при чтении вашей библиотеки Steam произошла ошибка :(",
    fr: "désolé mais il y a eu une erreur lors de la lecture de votre bibliothèque Steam :(",
  },
  language: {
    jp: "言語",
    es: "idioma",
    hi: "भाषा",
    ru: "язык",
    fr: "langue",
  },
};
